site_name: Metadata Documentation Portal
site_url: https://icpsr.github.io/metadata/
docs_dir: ../markdown
site_dir: ../site
nav:
  - Home: index.md
  - ICPSR Metadata Schema: icpsr_study_schema.md
  - ICPSR Metadata Style Guide: icpsr_style_guide.md
  - ICPSR Metadata Export API: icpsr_metadata_api.md 
  - ICPSR Metadata Change Process: request_change.md
theme:
  name: readthedocs
  analytics:
    gtag: G-PNP7RD0R04
  custom_dir: custom_theme/
  prev_next_buttons_location: none
  logo: ./assets/ICPSR_logo_rgb_white-01.png
  navigation_depth: 5
  sticky_navigation: true
  include_homepage_in_sidebar: false
extra_css: 
  - ./assets/style.css